[package]
name = "rustify"
version = "0.1.0"
authors = ["kgeronim <kevin.geronimo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.0-alpha.6"
serde = { version = "1.0", features = ["derive"] }

[dependencies.reqwest]
version = "0.10.0-alpha.2"
default-features = false

features = ["json"]