[package]
name = "cbpro"
version = "0.1.0"
authors = ["kgeronim <kevin.geronimo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.0-alpha.6"
serde_json = "1.0.42"
reqwest = { version = "0.10.0-alpha.2", features = ["json"] }
futures = "0.3.1"
tokio-timer = "0.3.0-alpha.5"
chrono = "0.4.10"
serde = { version = "1.0.103", features = ["derive"] }